# Generated by Django 2.1.7 on 2019-08-03 10:24

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('const_nam', models.CharField(max_length=50)),
                ('const_no', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('county_nam', models.CharField(max_length=50)),
                ('lukemia', models.SmallIntegerField()),
                ('cervical', models.IntegerField()),
                ('lung', models.IntegerField()),
                ('throat', models.IntegerField()),
                ('prostate', models.IntegerField()),
                ('total', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('breast', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'county',
                'managed': False,
            },
        ),
    ]
