# Generated by Django 2.2.5 on 2019-10-03 09:46

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('cancer_typ', models.CharField(blank=True, max_length=254, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('const_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('county_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('nhif', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=3)),
                ('cancer_sta', models.BigIntegerField(blank=True, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('M', 'Medication'), ('T', 'Breach')], max_length=3)),
                ('home_visit', models.BigIntegerField(blank=True, null=True)),
                ('referral', models.CharField(choices=[('HS', 'Hospital'), ('DR', 'Doctor'), ('S', 'Self')], max_length=3)),
                ('chemothera', models.BigIntegerField(blank=True, null=True)),
                ('events', models.BigIntegerField(blank=True, null=True)),
                ('firstvisit', models.CharField(blank=True, max_length=254, null=True)),
                ('drug', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_numb', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Stage 4')])),
                ('hospital', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('S', 'Seminars'), ('A', 'Awareness Campaign')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='download.png', upload_to='profile_pictures')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
