# Generated by Django 2.2.5 on 2019-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_caregiver_diet_doctorprofile_drugs_events_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
