# Generated by Django 2.2.5 on 2019-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190408_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.TextField(default='Doctor by Profession'),
        ),
    ]
