# Generated by Django 2.2.5 on 2019-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='+254740368934', max_length=18),
        ),
    ]
